BRMP-12794: GTM code commit, (dup) header and index
GSA/dx-solutionid-web pull request #20
Opened 2021-04-01 14:17 UTC by pramodganore

2021-04-01 14:18 UTC, dsomalaraju approved these changes

2021-04-01 15:40 UTC, chinchalinchin approved these changes

2021-04-05 14:26 UTC, pramodganore commented on frontend/src/index.html
> +
duplicate (in addition to the angular route (npm package)

2021-04-05 14:26 UTC, pramodganore commented on frontend/src/app/shared/header/header.component.html
> +  gtag('config', '{{GTM_TRACKING_ID}}', {'anonymizeIp': true}, {'forceSSL': true}, {'tansport': beacon});
Duplicate in addition to angular npm package. this code seems to vanish when i compile not sure why.

2021-04-05 14:31 UTC, dsomalaraju approved these changes

2021-04-05 14:40 UTC, chinchalinchin commented
might want to open a pr for development too.

2021-04-05 14:46 UTC, ccslowmo commented on frontend/src/app/shared/header/header.component.html
> +  gtag('config', '{{GTM_TRACKING_ID}}', {'anonymizeIp': true}, {'forceSSL': true}, {'tansport': beacon});
@pramodganore - embedding <script> tags in angular component html is uncommon, and angular will remove them when it compiles.

2021-04-05 17:45 UTC, ccslowmo approved these changes

2021-04-05 17:58 UTC, pramodganore commented
> might want to open a pr for development too.

Will do

2021-04-06 16:18 UTC, dsomalaraju approved these changes

2021-04-06 19:17 UTC, ccslowmo requested changes
tag manager is breaking application, will try to fix

2021-04-08 20:21 UTC, closed without merging